### ISSUE TITLE
publicize getinfo removal

### ISSUE THREAD

**Issue by roarde** [myriadteam/myriadcoin#130]
Many merchants, and some pools and exchanges, are still running Bitcoin 0.14.x. They have no experience working without the getinfo call that is removed in 0.16. It's still one of the more regularly used RPC calls.           
                       
There should be better notification of the change at Myriadcoin 0.16 release time. I suggest a mention of it on the release page as one part of that.

**Comment by cryptapus** [comment]
noted on the release page
