### ISSUE TITLE
Restore getinfo

### ISSUE THREAD

**Issue by cryptapus** [myriadteam/myriadcoin#148]
Some users wish to have the rpc `getinfo` restored. It has been deprecated and removed upstream.

Note that the information in `getinfo` (and much more detailed information) can be found via `getblockchaininfo`, `getnetworkinfo`, `getmininginfo`, and `getwalletinfo`.

**Comment by roarde** [comment]
Several libraries use getinfo call to determine whether a daemon/wallet is up-to-date with the network. Using getnetworkinfo for version, protocolversion, and connections, plus getblockcount for current height, will plug directly in for nearly all these cases.       
            
This will also work for versions prior to 16.x, so the same procedure can still be used for "all" bitcoin-based currencies.

**Comment by cryptapus** [comment]
This issue has been communicated to me out-of-band by one user so far. Since `v0.14.5.0` has `getinfo` and can get backports going forward for the foreseeable future I'm adding the `wontfix` label. Unless we get more feedback on why this is necessary I propose we give time to support software getting updated to use the expanded informational rpc calls.

**Comment by cryptapus** [comment]
Since this is a `wontfix`, I plan on closing it if/when `0.18` is released.
