### ISSUE TITLE
0.16 missing `getauxblock`

### ISSUE THREAD

**Issue by cryptapus** [myriadteam/myriadcoin#149]
The latest `0.16` based release does not have the `getauxblock` rpc call.

The `0.16` branch does not include the `getauxblock` rpc call as it has been replaced by namecoin with `createauxblock <address>` and `submitauxblock ...`.

There is currently no plan to restore `getauxblock` as Myriadcoin has a backported `0.14` release that does include `getauxblock`. (`v0.14.5.0` for the latest release.)

**Comment by cryptapus** [comment]
Since this is a `wontfix`, I plan on closing it if/when `0.18` is released.

**Comment by roarde** [comment]
Could we leave this as wontfix, but also keep it open (as with getblocktemplate)? I still get questions on this, and have to look it up every time
