### ISSUE TITLE
multiple R_X86_64_32S errors

### ISSUE THREAD

**Issue by cryptapus** [myriadteam/myriadcoin#2]
v0.11.2: On two different Debian Jessie machines I get:

    make[1]: Entering directory '/home/xxx/tmp/myriadcoin/src'
    make[2]: Entering directory '/home/xxx/tmp/myriadcoin/src'
     CXXLD    myriadcoind
    /usr/bin/ld: crypto/libbitcoin_crypto.a(crypto_libbitcoin_crypto_a-echo.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
    crypto/libbitcoin_crypto.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    Makefile:2686: recipe for target 'myriadcoind' failed
    make[2]: *** [myriadcoind] Error 1
    make[2]: Leaving directory '/home/xxx/tmp/myriadcoin/src'
    Makefile:6810: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/home/xxx/tmp/myriadcoin/src'
    Makefile:622: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

and

    ...
      CXX      qt/qt_libbitcoinqt_a-moc_walletmodel.o
      CXX      qt/qt_libbitcoinqt_a-moc_walletview.o
      CXX      qt/qt_libbitcoinqt_a-qrc_bitcoin.o
      CXX      qt/qt_libbitcoinqt_a-qrc_bitcoin_locale.o
      CXXLD    myriadcoind
    /usr/bin/ld: crypto/libbitcoin_crypto.a(crypto_libbitcoin_crypto_a-echo.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
    crypto/libbitcoin_crypto.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    Makefile:2686: recipe for target 'myriadcoind' failed
    make[2]: *** [myriadcoind] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[2]: Leaving directory '/home/xxx/tmp/myriadcoin/src'
    Makefile:6810: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/home/xxx/tmp/myriadcoin/src'
    Makefile:622: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

I am attempting to build with:

    ./autogen.sh
    ./configure --with-incompatible-bdb
    make (or make -j4)

but have not had issues using --with-incompatible-bdb in the past and these don't look related...

**Comment by nzsquirrell** [comment]
can you re-run configure with:

CFLAGS="-fPIC" CPPFLAGS="-fPIC" ./configure --with-incompatible-bdb

I've seen these issues before on x64

**Comment by cryptapus** [comment]
Yep, that did it. Thanks!
