### ISSUE TITLE
start time of daemon too long

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [myriadteam/myriadcoin#31]
Currently, my MYR daemon 0.11.3.1 needs at least 4-5 mins until things get going.

I find that's too much - may be a wrong thought? What are your loading times ?

Can someone look into how/if the startup time can be decreased ? e.g. save (some of) the RAM state of  the daemon before exit to HD and load that at next start ?
other ideas ?

**Comment by nzsquirrell** [comment]
resolved / reduced in 0.14 tree under development
