### ISSUE TITLE
0.11 myriad-qt.exe crashing

### ISSUE THREAD

**Issue by VivaH** [myriadteam/myriadcoin#35]
At https://www.reddit.com/r/myriadcoin/comments/5u7wcs/myriadqt_crashes_on_windows_10_32bit_system_with/ i was asked to report an issue.

The myriad wallet is crashing after some time when it's running. In this case i started it in the evening and the next morning i got the error: Fout bij het lezen van de database, afsluiten. (Error on reading the database, closing).

See enclosed screenshots and the debug-log.

[debug.zip](https://github.com/myriadteam/myriadcoin/files/780930/debug.zip)

<img width="900" alt="myriad error" src="https://cloud.githubusercontent.com/assets/25825921/23032028/6a9647da-f473-11e6-840c-105860ee5a8a.png">

![schermopname 120](https://cloud.githubusercontent.com/assets/25825921/23032201/f654f154-f473-11e6-8415-971f02697fab.png)

![schermopname 121](https://cloud.githubusercontent.com/assets/25825921/23032237/0bc8abf2-f474-11e6-8491-2650602e8a7b.png)

![schermopname 122](https://cloud.githubusercontent.com/assets/25825921/23032244/131432e6-f474-11e6-89d8-42ff5f0bae66.png)

**Comment by cryptapus** [comment]
0.11 will most likely not see further development
