### ISSUE TITLE
0.14, 0.16: use of CBigNum fails (bignum.h) with openssl v1.1

### ISSUE THREAD

**Issue by cryptapus** [myriadteam/myriadcoin#42]
Noticed that CBigNum fails in chain.cpp on Debian Stretch. It seems that bignum.h is only used here once in GetGeometricMeanPrevWork(). (branch 0.14)

**Comment by nzsquirrell** [comment]
Yep, is needed to calculate n'th root, until we can have that implemented in some other biginteger library. need to have a test defined in configure.ac for it.

**Comment by cryptapus** [comment]
appears to be solved with
    sudo apt install libssl1.0-dev
however I suppose it will need to be addressed in the future.

**Comment by cryptapus** [comment]
`bignum.h` removed in `v0.16.4.1`. Backports to `0.14` have also been applied.
