### ISSUE TITLE
Can't run makefile

### ISSUE THREAD

**Issue by kirksteele** [myriadteam/myriadcoin#47]
Whenever I try to run make, I get the following error. I don't see any issues within the file as far as spacing..

`Makefile:8: *** missing separator.  Stop.`

Any idea's?

**Comment by cryptapus** [comment]
is this on the master branch?

what os/version/distro?

**Comment by kirksteele** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

**Comment by cryptapus** [comment]
Obviously you've followed the build instructions here:

https://github.com/myriadteam/myriadcoin

(you can use the  libdb5.x-dev and libdb5.x++-dev native packages, just use ./configure --with-incompatable-bdb below)
 
maybe the full output of the following would be useful as well:

    ./autogen.sh
    CFLAGS="-O2 -fPIC -DUSE_SSE2" CPPFLAGS="-O2 -fPIC -DUSE_SSE2" ./configure

**Comment by kirksteele** [comment]
So I am using bash on Ubuntu on Windows, had to install dos2unix via apt-get and now it looks like it runs, but I get:

`libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
.ibtoolize:   error: AC_CONFIG_MACRO_DIRS([build-aux/m4]) conflicts with ACLOCAL_AMFLAGS=-I build-aux/m4
autoreconf: libtoolize failed with exit status: 1`


Would this fall under the "other notes" Section? if so, where do I apply those configuration changes, in the make file?

**Comment by kirksteele** [comment]
Looks to be an issue with Debian.. Trying to find a fix.

**Comment by kirksteele** [comment]
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
.ibtoolize:   error: AC_CONFIG_MACRO_DIRS([build-aux/m4]) conflicts with ACLOCAL_AMFLAGS=-I build-aux/m4
autoreconf: libtoolize failed with exit status: 1

**Comment by cryptapus** [comment]
Which branch is this for?

**Comment by kirksteele** [comment]
I am trying .14

Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:6063: recipe for target 'myriadcoind-bitcoind.o' failed
make[2]: *** [myriadcoind-bitcoind.o] Error 4
make[2]: Leaving directory '/root/myriadcoin/src'
Makefile:6941: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/myriadcoin/src'
Makefile:634: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by cryptapus** [comment]
Since you've opened this issue, many of the makefiles have been in flux. Sounds like you're mostly sorted now?

**Comment by kirksteele** [comment]
Yez.
