### ISSUE TITLE
0.14: chainsplit at block 2225353

### ISSUE THREAD

**Issue by cryptapus** [myriadteam/myriadcoin#68]
For posterity if nothing else, I'll put my findings here to discuss the recent chain split that was observed on 0.14.2.1.

At block 2225353 a block was accepted by 0.11 nodes but was then reorged by 0.14 nodes. Here is the log from the event for both nodes:

v0.11.3.2:

    2017-10-27 xx:21:43 UpdateTip: new best=84606d10f0085195d43e67504799c731e00b14f6bbfb2a61067b81568a642af3 height=2225352 algo=5 (yescrypt) log2_work=251.68825 tx=5268420 date=2017-10-27 xx:21:29 progress=1.000000 cache=0.0MiB(14tx) 
    2017-10-27 xx:21:52 UpdateTip: new best=396145cced4ce1b8458deee448e29ae121dcc936db2c4b9050d03874ed5df45a height=2225353 algo=0 (sha256d) log2_work=251.68825 tx=5268421 date=2017-10-27 xx:21:44 progress=1.000000 cache=0.0MiB(15tx) 
    2017-10-27 xx:22:27 connection from x.x.x.x:47083 dropped (banned)

v0.14.2.1

    2017-10-27 xx:21:43 UpdateTip: new best=84606d10f0085195d43e67504799c731e00b14f6bbfb2a61067b81568a642af3 height=2225352 version=0x205a0a04 algo=5 (yescrypt) log2_work=251.68825 tx=5268420 date='2017-10-27 xx:21:29' progress=1.000000 cache=0.6MiB(1466tx) 
    2017-10-27 xx:21:52 UpdateTip: new best=396145cced4ce1b8458deee448e29ae121dcc936db2c4b9050d03874ed5df45a height=2225353 version=0x005a0104 algo=0 (sha256d) log2_work=251.68825 tx=5268421 date='2017-10-27 xx:21:44' progress=1.000000 cache=0.6MiB(1467tx) 
    2017-10-27 xx:21:52 UpdateTip: new best=84606d10f0085195d43e67504799c731e00b14f6bbfb2a61067b81568a642af3 height=2225352 version=0x205a0a04 algo=5 (yescrypt) log2_work=251.68825 tx=5268420 date='2017-10-27 xx:21:29' progress=1.000000 cache=0.6MiB(1467tx) 
    2017-10-27 xx:21:52 UpdateTip: new best=41cb07859e8a641db6e491cc66e91fe4bee05e44ce5918ead51e6a968b78620c height=2225353 version=0x205a0a04 algo=5 (yescrypt) log2_work=251.68825 tx=5268421 date='2017-10-27 xx:21:42' progress=1.0

The v0.14.2.1 chain was eventual abandoned, and consensus returned to the v0.11.3.2 chain.

**Comment by cryptapus** [comment]
Here is the getblock for 2225353 on v0.11.3.2:

    myriadcoin-cli getblock 396145cced4ce1b8458deee448e29ae121dcc936db2c4b9050d03874ed5df45a
    {
        "hash" : "396145cced4ce1b8458deee448e29ae121dcc936db2c4b9050d03874ed5df45a",
        "confirmations" : 335,
        "size" : 830,
        "height" : 2225353,
        "version" : 5898500,
        "pow_algo_id" : 0,
        "pow_algo" : "sha256d",
        "pow_hash" : "396145cced4ce1b8458deee448e29ae121dcc936db2c4b9050d03874ed5df45a",
        "merkleroot" : "bc7d96647ecfda24a5d025a29fe6afd1311e59a2ba5c4087030f28a74f97369b",
        "tx" : [
            "bc7d96647ecfda24a5d025a29fe6afd1311e59a2ba5c4087030f28a74f97369b"
        ],
        "time" : 1509074504,
        "nonce" : 0,
        "bits" : "180bc6b4",
        "difficulty" : 93365970071.55058289,
        "chainwork" : "0ce4000000000000000000000000000000000000000000dfe63de0fc7ea383b4",
        "auxpow" : {
            "tx" : {
                "hex" : "01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff5903d0970741d67ca992401af241d67ca991858b8f2f4254432e544f502f4e59412ffabe6d6d16870e4c05b697b94ccf47266760e487b118257d5a754154ccbba77e08c406888000000000000000d40006551b5b000000000000ffffffff013a66844a000000001976a9146d5bda2ee1b2ae0160c17d33f56218c7a1d37fce88ac00000000",
                "txid" : "102806bf6c5374d56616999809d34b1355f4d23cc03de79536d9ae50573918c2",
                "version" : 1,
                "locktime" : 0,
                "vin" : [
                    {
                        "coinbase" : "03d0970741d67ca992401af241d67ca991858b8f2f4254432e544f502f4e59412ffabe6d6d16870e4c05b697b94ccf47266760e487b118257d5a754154ccbba77e08c406888000000000000000d40006551b5b000000000000",
                        "sequence" : 4294967295
                    }
                ],
                "vout" : [
                    {
                        "value" : 12.50190906,
                        "n" : 0,
                        "scriptPubKey" : {
                            "asm" : "OP_DUP OP_HASH160 6d5bda2ee1b2ae0160c17d33f56218c7a1d37fce OP_EQUALVERIFY OP_CHECKSIG",
                            "hex" : "76a9146d5bda2ee1b2ae0160c17d33f56218c7a1d37fce88ac",
                            "reqSigs" : 1,
                            "type" : "pubkeyhash",
                            "addresses" : [
                                "MHsPvM8S2PWtxuixwrdt6qB2AWnXUCyv9Q"
                            ]
                        }
                    }
                ],
                "blockhash" : "0000000000000000047687084e4023edcaab58caf19bea593c7a1b4f63260083"
            },
            "index" : 0,
            "chainindex" : 80,
            "merklebranch" : [
                "db061791313750a12a055644a9cc2f9b9aa7a7a20f351a35acf76f4bc03af781",
                "0aef3dcaa67a20924612ed6546593f9d67ce4d447cf4634124416221cf42b3e7",
                "09aac3719310664b720bcc877ee34193e41b86ef3237973bac43e36ba935b59e",
                "8ab5aa2bb1f11d88521e32c898c90e546d7ad9f7d76d42a6687edbfc7bc13c7c"
            ],
            "chainmerklebranch" : [
                "0000000000000000000000000000000000000000000000000000000000000000",
                "f98c4e9736d8eb8bb46299798906695c755369a3df99a93ffdded1713f1cf6e2",
                "48e55233b9707330def98c80a2105eaa5fac8f687d872ffb4b4741fa2bdb247d",
                "45026d8edaa7259b19e26f4fbdf78db3dba024b1d9dd4e9b475b5e9a4c84fdd1",
                "529c628e383e21eacca3490c3be774dd494d5b029e2f99f83b00e9bc26d2d15a",
                "de0f59dd5a83f64041ff13d9ec4a7497d79910ac0d74f089e21f8ef90388d379",
                "2ec408e767cc721c8329b6fb46b45e6b9ee723ac8c846f8386b96dd02315c62d"
            ],
            "parentblock" : "0000002047858059afd0fa3c57fe9408d07dce657e3fdfaef71e0e030000000000000000431e0a2b965104a1631ee502a114ca51b11a0d1c354b75806351ee5f32ed7efb46a6f25997361018e58ebc0a"
        },
        "previousblockhash" : "84606d10f0085195d43e67504799c731e00b14f6bbfb2a61067b81568a642af3",
        "nextblockhash" : "ce3e2ae540b1d22cd6038cd63210aec91e22abb9549cc78375205eea74327ca2"
    }

**Comment by cryptapus** [comment]
Here is the getblock for 2225353 on v0.14.2.1 (now since abandoned):

    myriadcoin-cli getblock 41cb07859e8a641db6e491cc66e91fe4bee05e44ce5918ead51e6a968b78620c
    {
      "hash": "41cb07859e8a641db6e491cc66e91fe4bee05e44ce5918ead51e6a968b78620c",
      "confirmations": 174,
      "strippedsize": 280,
      "size": 280,
      "weight": 1120,
      "height": 2225353,
      "version": 542771716,
      "versionHex": "205a0a04",
      "merkleroot": "627cd0e48d6e12a0aa096983c8cff15314f0544d6a402fd5db04b76ae7d3bfca",
      "tx": [
        "627cd0e48d6e12a0aa096983c8cff15314f0544d6a402fd5db04b76ae7d3bfca"
      ],
      "time": 1509074502,
      "mediantime": 1509074280,
      "nonce": 3608215680,
      "bits": "1d03e061",
      "pow_hash": "000000034e4843ea3dd434f5e6b53e9c8641c33c33f96154f3e0cb3e1e229516",
      "pow_algo_id": 5,
      "pow_algo": "yescrypt",
      "difficulty": 0.2579620466917799,
      "chainwork": "0ce400000000000000000000000000000000000000000074f3044d91b065ef9b",
      "previousblockhash": "84606d10f0085195d43e67504799c731e00b14f6bbfb2a61067b81568a642af3",
      "nextblockhash": "c33d93a88486f03546d85277e423c33ee761d804146a6a2cae34e9dc2ce8cad0"
    }

**Comment by cryptapus** [comment]
Perhaps the key is in the chainwork calculation.

looking at the valid 2225353 block (slightly edited to remove some whitespace),

for v0.11.3.2:

    "chainwork": "0ce4000000000000000000000000000000000000000000dfe63de0fc7ea383b4"

for v0.14.2.1:

    "chainwork": "0ce400000000000000000000000000000000000000000074f2a5dcacb326299b"

and with an updated chainwork calc with c417658:

    "chainwork": "0ce4000000000000000000000000000000000000000000dfe63de0fc7ea383b4"

even though chainwork is held for internal validation to the node, it might be significantly different between versions at such a high chainwork in mainnet to cause a miscalculation.

**Comment by cryptapus** [comment]
This chainsplit and an additional previous one noticed in #66 happened surrounding a yescrypt block. One theory is due to yescrypt's contribution to GetGeometricMeanPrevWork(), it might be the first algo to be affected by perturbations in chainwork.

**Comment by nzsquirrell** [comment]
I saw pretty much the same issues with an early build of Unitus. See https://github.com/unitusdev/unitus/commit/48f20b70842b9bf8103dac7c3eab2d0830f594c8 for what was changed to ensure the work calculation was consistent between versions

**Comment by cryptapus** [comment]
Thanks, yes, I'm sure that's where I pulled it in from.

Looking at Unitus block 400000 (sorry, latest one I have):

v0.9:

    "chainwork" : "13b3500000000000000000000000000000000000000000000fdf8839b20c44b9"

v0.14:

    "chainwork" : "13b3500000000000000000000000000000000000000000000fdf8839b20c44b9"

and your chainwork is consistent. I'll need to dig in a little deeper on why `pindex = pindex->pprev;` was not necessary here. Perhaps since Myriad went from 0.9 -> 0.11 -> 0.14 it just wasn't noticed on 0.11. The `NUM_ALGOS_IMPL` additions look to be distinct, but critical fixes.

**Comment by cryptapus** [comment]
An update including these changes has been released in v0.14.2.3-rc0.

https://github.com/myriadteam/myriadcoin/releases/tag/v0.14.2.3-rc0

**Comment by cryptapus** [comment]
v0.14.2.3 released with these changes.

https://github.com/myriadteam/myriadcoin/releases/tag/v0.14.2.3

**Comment by cryptapus** [comment]
v0.14.2.3 achieved majority block share at block ~2279000
