### ISSUE TITLE
Myriad core not loading

### ISSUE THREAD

**Issue by BumpyQ** [myriadteam/myriadcoin#74]
When attempting to open myriad-qt, during process of loading block index, a runtime error appears. 

file validation.cpp line 2452

!setblockindexcandidates.empty()

loading fails, repeated 3 times. win 10 64bit

**Comment by cryptapus** [comment]
Have you tried with

`myriad-qt.exe -reindex`

**Comment by cryptapus** [comment]
Also, perhaps you might try removing all but your wallet.dat and redownloading.

**Comment by BumpyQ** [comment]
It looks like the reinstall will work fine, thank you. I had nothing in the wallet yet, so no worries there.
