### ISSUE TITLE
Trying to host z-nomp with equihash on beta build 2

### ISSUE THREAD

**Issue by Simplexletalis** [myriadteam/myriadcoin#90]
Pool located at: http://cryptopop.club/
```

2018-02-08 08:16:44 [Pool]      [myriadcoin] (Thread 1) Daemon is still syncing with network (download blockchain) - server will be started once synced
2018-02-08 08:16:44 [Pool]      [myriadcoin] (Thread 1) Downloaded NaN% of blockchain from 3 peers
2018-02-08 08:16:44 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2018-02-08 08:16:44 [Pool]      [myriadcoin] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2018-02-08 08:16:49 [Pool]      [myriadcoin] (Thread 1) Downloaded NaN% of blockchain from 3 peers

```

Using trupvot CCminer with an nvidia 1070, stratum just disconnects.

Was the genesis block mined? Is there a beta2 host that is reliable for mip1?

**Comment by Simplexletalis** [comment]
```
./myriadcoin-cli getblockcount
0

```

99% sure genesis block is busted or chain is broke somewhere.

**Comment by TheCannings** [comment]
Just to add to this, the blocks weren't the issue with the:

myriadcoin-cli generate 

I was able to get some blocks into the chain then came some issues with znomp where it uses some rpc calls we don't have such as getblocksubsidy I don't know if this is something all pools use or just znomp however so it may be inconsequential as all it does is return the block reward and founder fee for the next block which makes no difference to us.

After hardcoding the block reward into the nodejs I got to the next error of:

ZcashMiner::parseJob(): Invalid or unsupported block header version

which I think relates to what cryptapus just pr'd

**Comment by TheCannings** [comment]
Okay, so I have 2 miners working on the pool now, that seems not bad only change I made was hard coding the response to getblocksubsidy into the znomp pool to be {"miner": 250, "Founder": 0}

However still getting the error of "Block does not start with a coinbase" which I think is something more or a myriad equihash mismatch but i'll have to pass that on up to @cryptapus or @8bitcoder as i'm far out my depth now.

**Comment by TheCannings** [comment]
Just as an extension here is the blockHex submitted by znomp using submitblock,

https://hastebin.com/raw/pajeyenavi

this still returned the error of block does not start with a coinbase

**Comment by roarde** [comment]
When too much time goes by between blocks, daemon will seem to hang at sync. Generating a block solves this. Set the daemon's algo to sha256d, scrypt, groestl, or (for now) qubit and issue `myriadcoin-cli generate 1`.

Equihash generation by the daemon isn't working yet; qubit will be swapped out for yescrypt at block 601.

The Equihash N and K parameters weren't being set for testnet. Daemon needs to be rebuilt with commit 654bb8f (pull request #92) included. That fixes the "bad equihash parameters" error that was being thrown. Still cannot generate Equihash blocks directly with the daemon, but mining may work with miner and stratum properly configured.

I think Z-NOMP structures blocks for Zclassic by default. That means there can be a founders' reward and/or staking reward *before* the generation coinbase. The daemon rejects any submission that doesn't have the coinbase as its *first* transaction. The Zcash configuration that ships with Z-NOMP presents the same problem. No idea whether using the Komodo config for a template would solve that.

**Comment by roarde** [comment]
In attracting diverse pools to mine our Equihash, we'll approach both those created to hash Z-type coins and those who generally mine Bitcoin-based currencies. That means providing notes on how to adapt either style pool would be useful.

I think that's not only a separate issue, it may be a whole 'nother repo.

Suggestion: We test and document one stratum for ourselves to use in testing, then take up explaining what changes various miners and pools may need elsewhere.

That's not a suggestion to drop this discussion. There's some momentum to have Z-NOMP or UNOMP provide that test-stratum. Whatever works soon and can be easily shared, I figure.

**Comment by roarde** [comment]
There are mined Scrypt blocks in the chain, which used node-stratum. Which pool software was used for this?

**Comment by phantanthanh1996** [comment]
So could anyone pls tell me how to fix it?

**Comment by cryptapus** [comment]
I believe we will have to refactor much of equihash items with the introduction of 0.16 if we decide to revisit. I plan to close this issue in ~1 week if there are no objections.
